// 2020-2026 四六级高频词汇数据
// 词根词缀 + 谐音联想 + 拆分联想 巧记法

export interface WordSeed {
  word: string;
  pronunciation: string;
  meaning: string;
  mnemonic: string;
  exampleSentence: string;
  exampleTranslation: string;
  level: string;
  tags: string;
  status: string;
}

export interface PassageSeed {
  title: string;
  content: string;
  translation: string;
  highlightedWordIds: string;
  level: string;
  tags: string;
  status: string;
}

// ============================================================
// CET-4 高频词汇 (2020-2026 真题高频)
// ============================================================
export const cet4Words: WordSeed[] = [
  // --- A ---
  {
    word: "abandon",
    pronunciation: "/əˈbændən/",
    meaning: "v. 放弃，抛弃；放纵",
    mnemonic: "a(一个)+band(乐队)+on(在演出)→一个乐队在演出时抛弃了主唱→放弃",
    exampleSentence: "The captain refused to abandon the sinking ship.",
    exampleTranslation: "船长拒绝放弃正在下沉的船。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "absorb",
    pronunciation: "/əbˈzɔːrb/",
    meaning: "v. 吸收；吸引（注意力）",
    mnemonic: "ab(离开)+sorb(吸)→把东西吸走→吸收；be absorbed in 全神贯注于",
    exampleSentence: "Plants absorb nutrients from the soil.",
    exampleTranslation: "植物从土壤中吸收养分。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "abuse",
    pronunciation: "/əˈbjuːz/",
    meaning: "v./n. 滥用；虐待；辱骂",
    mnemonic: "ab(偏离)+use(使用)→偏离正常使用→滥用",
    exampleSentence: "We should not abuse our power in any situation.",
    exampleTranslation: "在任何情况下我们都不应滥用权力。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "access",
    pronunciation: "/ˈækses/",
    meaning: "n. 进入；通道 v. 访问，获取",
    mnemonic: "ac(朝向)+cess(走)→走向某处→进入，访问；have access to 有…的途径",
    exampleSentence: "Students have free access to the online library.",
    exampleTranslation: "学生可以免费访问在线图书馆。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "accommodate",
    pronunciation: "/əˈkɒmədeɪt/",
    meaning: "v. 容纳；为…提供住宿；适应",
    mnemonic: "ac+com(共同)+mod(模式)+ate→共同模式→需要容纳和适应",
    exampleSentence: "The hotel can accommodate up to 500 guests.",
    exampleTranslation: "这家酒店最多可容纳500位客人。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "account",
    pronunciation: "/əˈkaʊnt/",
    meaning: "n. 账户；解释 v. 说明；占比",
    mnemonic: "ac(加强)+count(数)→加强计算→账目；account for 解释，占比",
    exampleSentence: "Social media accounts for a large part of our daily time.",
    exampleTranslation: "社交媒体占据了我们日常时间的很大一部分。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "achieve",
    pronunciation: "/əˈtʃiːv/",
    meaning: "v. 实现，达到；获得",
    mnemonic: "a(加强)+chieve(chief 首领)→成为首领→达到目标",
    exampleSentence: "She worked hard to achieve her dream of becoming a doctor.",
    exampleTranslation: "她努力实现了成为医生的梦想。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "adapt",
    pronunciation: "/əˈdæpt/",
    meaning: "v. 适应；改编",
    mnemonic: "ad(朝向)+apt(适合)→使适合→适应；adapt to 适应于",
    exampleSentence: "It takes time to adapt to the new environment.",
    exampleTranslation: "适应新环境需要时间。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "adjust",
    pronunciation: "/əˈdʒʌst/",
    meaning: "v. 调整，调节；适应",
    mnemonic: "ad(朝向)+just(刚好)→调到刚好→调整；adjust to 适应",
    exampleSentence: "You can adjust the volume with this button.",
    exampleTranslation: "你可以用这个按钮调节音量。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "adopt",
    pronunciation: "/əˈdɒpt/",
    meaning: "v. 采用；收养",
    mnemonic: "ad(朝向)+opt(选择)→选择采取→采用/收养",
    exampleSentence: "Many companies have adopted remote working policies.",
    exampleTranslation: "许多公司已经采用了远程办公政策。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },

  // --- B ---
  {
    word: "balance",
    pronunciation: "/ˈbæləns/",
    meaning: "n. 平衡；余额 v. 使平衡",
    mnemonic: "ba(ba 爸)+lance(枪)→爸爸拿枪要保持平衡→平衡",
    exampleSentence: "It's important to keep a balance between work and life.",
    exampleTranslation: "保持工作与生活的平衡很重要。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "barrier",
    pronunciation: "/ˈbæriər/",
    meaning: "n. 障碍；屏障",
    mnemonic: "bar(栏杆)+rier→栏杆形成的障碍→屏障；language barrier 语言障碍",
    exampleSentence: "Language is no longer a barrier thanks to translation apps.",
    exampleTranslation: "有了翻译软件，语言不再是障碍。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "benefit",
    pronunciation: "/ˈbenɪfɪt/",
    meaning: "n. 利益，好处 v. 有益于",
    mnemonic: "bene(好)+fit(做)→做好事→有益；benefit from 从…中获益",
    exampleSentence: "Regular exercise benefits both body and mind.",
    exampleTranslation: "定期锻炼有益于身心。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "budget",
    pronunciation: "/ˈbʌdʒɪt/",
    meaning: "n. 预算 v. 做预算",
    mnemonic: "bud(花苞)+get(得到)→花苞要得到养护需要预算→预算",
    exampleSentence: "We need to plan our monthly budget carefully.",
    exampleTranslation: "我们需要仔细规划每月预算。",
    level: "CET4", tags: '["名词","动词","真题"]', status: "published",
  },

  // --- C ---
  {
    word: "campaign",
    pronunciation: "/kæmˈpeɪn/",
    meaning: "n. 运动，活动；战役",
    mnemonic: "camp(营地)+aign→在营地策划运动→运动，战役",
    exampleSentence: "The government launched a campaign against smoking.",
    exampleTranslation: "政府发起了一场禁烟运动。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "capable",
    pronunciation: "/ˈkeɪpəbl/",
    meaning: "adj. 有能力的",
    mnemonic: "cap(抓)+able(能)→能抓住的→有能力的；be capable of 能够",
    exampleSentence: "She is capable of handling multiple tasks at once.",
    exampleTranslation: "她有能力同时处理多项任务。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "challenge",
    pronunciation: "/ˈtʃælɪndʒ/",
    meaning: "n. 挑战 v. 向…挑战",
    mnemonic: "chall(谐音：拆了)+enge→把困难拆了→挑战",
    exampleSentence: "Learning a new language is an exciting challenge.",
    exampleTranslation: "学习一门新语言是一个令人兴奋的挑战。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "circumstance",
    pronunciation: "/ˈsɜːkəmstəns/",
    meaning: "n. 环境，情况（常用复数）",
    mnemonic: "circum(环绕)+stance(站立)→环绕站立的东西→环境；under no circumstances 决不",
    exampleSentence: "Under no circumstances should we give up hope.",
    exampleTranslation: "在任何情况下我们都不应放弃希望。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "communicate",
    pronunciation: "/kəˈmjuːnɪkeɪt/",
    meaning: "v. 交流；传达",
    mnemonic: "com(共同)+muni(服务)+cate→共同服务需要交流→交流",
    exampleSentence: "We communicate with each other through social media.",
    exampleTranslation: "我们通过社交媒体互相交流。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "community",
    pronunciation: "/kəˈmjuːnəti/",
    meaning: "n. 社区；团体",
    mnemonic: "com(共同)+muni(服务)+ty→共同服务的地方→社区",
    exampleSentence: "The local community supports the new environmental project.",
    exampleTranslation: "当地社区支持这个新的环保项目。",
    level: "CET4", tags: '["高频词","名词","真题"]', status: "published",
  },
  {
    word: "compete",
    pronunciation: "/kəmˈpiːt/",
    meaning: "v. 竞争；比赛",
    mnemonic: "com(共同)+pete(追求)→共同追求→竞争；compete with/against 与…竞争",
    exampleSentence: "Athletes from all over the world compete in the Olympics.",
    exampleTranslation: "来自世界各地的运动员在奥运会上竞争。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "concentrate",
    pronunciation: "/ˈkɒnsntreɪt/",
    meaning: "v. 集中；专注",
    mnemonic: "con(一起)+centr(中心)+ate→一起到中心→集中；concentrate on 专注于",
    exampleSentence: "I need to concentrate on my studies before the exam.",
    exampleTranslation: "考试前我需要专注于学习。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "confident",
    pronunciation: "/ˈkɒnfɪdənt/",
    meaning: "adj. 自信的；确信的",
    mnemonic: "con(完全)+fid(信任)+ent→完全信任自己→自信的",
    exampleSentence: "She felt confident about passing the interview.",
    exampleTranslation: "她对通过面试充满信心。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "consequence",
    pronunciation: "/ˈkɒnsɪkwəns/",
    meaning: "n. 结果，后果",
    mnemonic: "con(一起)+sequ(跟随)+ence→一起跟随而来的东西→后果",
    exampleSentence: "Every choice we make has consequences.",
    exampleTranslation: "我们做的每个选择都有后果。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "consume",
    pronunciation: "/kənˈsjuːm/",
    meaning: "v. 消费；消耗",
    mnemonic: "con(完全)+sume(拿取)→完全拿走→消费，消耗；time-consuming 耗时的",
    exampleSentence: "We consume a lot of energy every day.",
    exampleTranslation: "我们每天消耗大量能源。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "contribute",
    pronunciation: "/kənˈtrɪbjuːt/",
    meaning: "v. 贡献；捐献；导致",
    mnemonic: "con(一起)+tribute(给予)→一起给予→贡献；contribute to 有助于，导致",
    exampleSentence: "Everyone should contribute to protecting the environment.",
    exampleTranslation: "每个人都应该为保护环境做出贡献。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "convenient",
    pronunciation: "/kənˈviːniənt/",
    meaning: "adj. 方便的",
    mnemonic: "con(一起)+veni(来)+ent→一起来→方便的（东西都聚在一起）",
    exampleSentence: "Online shopping is very convenient for busy people.",
    exampleTranslation: "网购对忙碌的人来说非常方便。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "convince",
    pronunciation: "/kənˈvɪns/",
    meaning: "v. 说服，使确信",
    mnemonic: "con(完全)+vince(征服)→完全征服→说服",
    exampleSentence: "I tried to convince him to join our team.",
    exampleTranslation: "我试图说服他加入我们的团队。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "crash",
    pronunciation: "/kræʃ/",
    meaning: "v./n. 碰撞；崩溃；暴跌",
    mnemonic: "c+rash(冲)→冲撞→碰撞，崩溃；car crash 车祸",
    exampleSentence: "The stock market crashed in 2008.",
    exampleTranslation: "2008年股市崩盘了。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "critical",
    pronunciation: "/ˈkrɪtɪkl/",
    meaning: "adj. 批评的；关键的；危急的",
    mnemonic: "crit(判断)+ical→做出判断的→批评的/关键的",
    exampleSentence: "It is critical that we find a solution quickly.",
    exampleTranslation: "关键是我们必须尽快找到解决方案。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },

  // --- D ---
  {
    word: "decline",
    pronunciation: "/dɪˈklaɪn/",
    meaning: "v. 下降；婉拒 n. 减少",
    mnemonic: "de(向下)+cline(倾斜)→向下倾斜→下降，减少",
    exampleSentence: "The number of smokers has been declining in recent years.",
    exampleTranslation: "近年来吸烟者数量一直在下降。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "decorate",
    pronunciation: "/ˈdekəreɪt/",
    meaning: "v. 装饰，装潢",
    mnemonic: "decor(装饰品)+ate(动词后缀)→装饰",
    exampleSentence: "They decorated the room with flowers and balloons.",
    exampleTranslation: "他们用鲜花和气球装饰了房间。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "demonstrate",
    pronunciation: "/ˈdemənstreɪt/",
    meaning: "v. 展示；证明；示威",
    mnemonic: "de(完全)+monstr(展示)+ate→完全展示→证明，展示",
    exampleSentence: "The experiment demonstrates the law of gravity.",
    exampleTranslation: "这个实验证明了万有引力定律。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "deserve",
    pronunciation: "/dɪˈzɜːv/",
    meaning: "v. 值得，应得",
    mnemonic: "de(完全)+serve(服务)→完全值得服务→值得",
    exampleSentence: "You deserve the award after all your hard work.",
    exampleTranslation: "经过所有努力，你值得这个奖。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "despite",
    pronunciation: "/dɪˈspaɪt/",
    meaning: "prep. 尽管，不管",
    mnemonic: "de(向下)+spite(看)→向下看(不放在眼里)→尽管；despite the fact that 尽管",
    exampleSentence: "Despite the rain, the game continued as planned.",
    exampleTranslation: "尽管下雨，比赛还是按计划进行。",
    level: "CET4", tags: '["高频词","介词","真题"]', status: "published",
  },
  {
    word: "determine",
    pronunciation: "/dɪˈtɜːmɪn/",
    meaning: "v. 决定；确定；下决心",
    mnemonic: "de(向下)+term(边界)+ine→定下边界→决定；be determined to 决心",
    exampleSentence: "We need to determine the cause of the problem.",
    exampleTranslation: "我们需要确定问题的原因。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "digital",
    pronunciation: "/ˈdɪdʒɪtl/",
    meaning: "adj. 数字的，数码的",
    mnemonic: "digit(数字)+al(形容词后缀)→数字的",
    exampleSentence: "Digital technology has changed the way we live.",
    exampleTranslation: "数字技术改变了我们的生活方式。",
    level: "CET4", tags: '["形容词","热点","真题"]', status: "published",
  },
  {
    word: "distinguish",
    pronunciation: "/dɪˈstɪŋɡwɪʃ/",
    meaning: "v. 区分，辨别",
    mnemonic: "di(分开)+stingu(刺)+ish→用刺分开→区分；distinguish A from B 区分A和B",
    exampleSentence: "It's hard to distinguish real news from fake news.",
    exampleTranslation: "很难区分真新闻和假新闻。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "diverse",
    pronunciation: "/daɪˈvɜːs/",
    meaning: "adj. 多样的，不同的",
    mnemonic: "di(分开)+verse(转向)→转开→不同的，多样的",
    exampleSentence: "Our university has a diverse student population.",
    exampleTranslation: "我们大学有来自不同背景的学生群体。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },

  // --- E ---
  {
    word: "economy",
    pronunciation: "/ɪˈkɒnəmi/",
    meaning: "n. 经济；节约",
    mnemonic: "eco(家)+nomy(管理)→管理家业→经济",
    exampleSentence: "The global economy has faced many challenges since 2020.",
    exampleTranslation: "自2020年以来，全球经济面临了许多挑战。",
    level: "CET4", tags: '["高频词","名词","热点","真题"]', status: "published",
  },
  {
    word: "efficient",
    pronunciation: "/ɪˈfɪʃnt/",
    meaning: "adj. 高效的",
    mnemonic: "ef(出)+fici(做)+ent→做出效果的→高效的",
    exampleSentence: "This new method is more efficient than the old one.",
    exampleTranslation: "这种新方法比旧方法更高效。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "eliminate",
    pronunciation: "/ɪˈlɪmɪneɪt/",
    meaning: "v. 消除；淘汰",
    mnemonic: "e(出)+limin(门槛)+ate→丢出门槛外→消除，淘汰",
    exampleSentence: "We must eliminate all sources of pollution.",
    exampleTranslation: "我们必须消除所有污染源。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "embrace",
    pronunciation: "/ɪmˈbreɪs/",
    meaning: "v. 拥抱；欣然接受",
    mnemonic: "em(进入)+brace(胳膊)→进入胳膊→拥抱；embrace change 拥抱变化",
    exampleSentence: "We should embrace new technologies with an open mind.",
    exampleTranslation: "我们应该以开放的心态拥抱新技术。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "emerge",
    pronunciation: "/ɪˈmɜːdʒ/",
    meaning: "v. 出现，浮现",
    mnemonic: "e(出)+merge(沉没)→从沉没中出来→浮现，出现",
    exampleSentence: "New problems emerged after the policy was implemented.",
    exampleTranslation: "政策实施后出现了新问题。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "emphasis",
    pronunciation: "/ˈemfəsɪs/",
    meaning: "n. 强调，重点",
    mnemonic: "em(在…内)+phas(展示)+is→在里面展示→强调；put emphasis on 强调",
    exampleSentence: "The school puts great emphasis on character education.",
    exampleTranslation: "学校非常重视品格教育。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "encounter",
    pronunciation: "/ɪnˈkaʊntər/",
    meaning: "v./n. 遇到，遭遇",
    mnemonic: "en(使)+counter(相对)→使相对→遇到",
    exampleSentence: "We may encounter difficulties along the way.",
    exampleTranslation: "我们可能会在途中遇到困难。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "engage",
    pronunciation: "/ɪnˈɡeɪdʒ/",
    meaning: "v. 参与；吸引；订婚",
    mnemonic: "en(使)+gage(保证)→使做出保证→参与，投入；engage in 参与",
    exampleSentence: "Students should actively engage in class discussions.",
    exampleTranslation: "学生应该积极参与课堂讨论。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "environment",
    pronunciation: "/ɪnˈvaɪrənmənt/",
    meaning: "n. 环境",
    mnemonic: "en(在…中)+viron(环绕)+ment→环绕在周围的东西→环境",
    exampleSentence: "We all have a responsibility to protect the environment.",
    exampleTranslation: "我们都有责任保护环境。",
    level: "CET4", tags: '["高频词","名词","热点","真题"]', status: "published",
  },
  {
    word: "essential",
    pronunciation: "/ɪˈsenʃl/",
    meaning: "adj. 本质的；必不可少的",
    mnemonic: "ess(存在)+ential→存在的根本→本质的；be essential to 对…必不可少",
    exampleSentence: "Water is essential for all living things.",
    exampleTranslation: "水对所有生物都是必不可少的。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "eventually",
    pronunciation: "/ɪˈventʃuəli/",
    meaning: "adv. 最终，终于",
    mnemonic: "event(事件)+ually→事件发展到最后→最终",
    exampleSentence: "After many failures, he eventually succeeded.",
    exampleTranslation: "经过多次失败，他最终成功了。",
    level: "CET4", tags: '["副词","真题"]', status: "published",
  },
  {
    word: "evidence",
    pronunciation: "/ˈevɪdəns/",
    meaning: "n. 证据，迹象",
    mnemonic: "e(出)+vid(看)+ence→看出来→证据",
    exampleSentence: "There is no evidence to support this claim.",
    exampleTranslation: "没有证据支持这个说法。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "explore",
    pronunciation: "/ɪkˈsplɔːr/",
    meaning: "v. 探索；探究",
    mnemonic: "ex(出)+plore(喊叫)→喊出来→探索发现",
    exampleSentence: "The internet allows us to explore the world from home.",
    exampleTranslation: "互联网让我们可以在家探索世界。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },

  // --- F ---
  {
    word: "facility",
    pronunciation: "/fəˈsɪləti/",
    meaning: "n. 设施；能力；便利",
    mnemonic: "fac(做)+ility(容易)→让做事更容易的东西→设施",
    exampleSentence: "The school has excellent sports facilities.",
    exampleTranslation: "这所学校有极好的体育设施。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "feature",
    pronunciation: "/ˈfiːtʃər/",
    meaning: "n. 特征；特色 v. 以…为特色",
    mnemonic: "feat(做)+ure→做出来的东西→特征，特色",
    exampleSentence: "The new phone features an advanced camera system.",
    exampleTranslation: "这款新手机以先进的相机系统为特色。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "flexible",
    pronunciation: "/ˈfleksəbl/",
    meaning: "adj. 灵活的；柔韧的",
    mnemonic: "flex(弯曲)+ible(能)→能弯曲的→灵活的",
    exampleSentence: "A flexible schedule helps employees balance work and life.",
    exampleTranslation: "灵活的时间表帮助员工平衡工作和生活。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "focus",
    pronunciation: "/ˈfəʊkəs/",
    meaning: "v./n. 焦点，专注",
    mnemonic: "foc(焦点)+us→焦点；focus on 聚焦于，专注于",
    exampleSentence: "Let's focus on solving the most urgent problems first.",
    exampleTranslation: "让我们先专注于解决最紧急的问题。",
    level: "CET4", tags: '["高频词","动词","名词","真题"]', status: "published",
  },
  {
    word: "fundamental",
    pronunciation: "/ˌfʌndəˈmentl/",
    meaning: "adj. 基本的，根本的",
    mnemonic: "funda(基础)+ment+al→基础的→基本的",
    exampleSentence: "Reading is a fundamental skill for all learning.",
    exampleTranslation: "阅读是所有学习的基本技能。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },

  // --- G ---
  {
    word: "generate",
    pronunciation: "/ˈdʒenəreɪt/",
    meaning: "v. 产生；生成",
    mnemonic: "gener(产生)+ate→产生，生成",
    exampleSentence: "Wind turbines generate electricity from the wind.",
    exampleTranslation: "风力发电机利用风来发电。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "global",
    pronunciation: "/ˈɡləʊbl/",
    meaning: "adj. 全球的；全面的",
    mnemonic: "glob(球)+al→球形的→全球的；global warming 全球变暖",
    exampleSentence: "Climate change is a global issue that affects everyone.",
    exampleTranslation: "气候变化是影响每个人的全球性问题。",
    level: "CET4", tags: '["高频词","形容词","热点","真题"]', status: "published",
  },
  {
    word: "guarantee",
    pronunciation: "/ˌɡærənˈtiː/",
    meaning: "v./n. 保证，担保",
    mnemonic: "guar(保护)+antee→提供保护→保证",
    exampleSentence: "Hard work doesn't guarantee success, but it helps.",
    exampleTranslation: "努力不一定保证成功，但有帮助。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },

  // --- H-I ---
  {
    word: "identify",
    pronunciation: "/aɪˈdentɪfaɪ/",
    meaning: "v. 识别；确认；认同",
    mnemonic: "ident(相同)+ify(使)→使相同→识别，认同；identify with 认同",
    exampleSentence: "Can you identify the man in this photo?",
    exampleTranslation: "你能认出这张照片里的男人吗？",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "impact",
    pronunciation: "/ˈɪmpækt/",
    meaning: "n./v. 影响；冲击",
    mnemonic: "im(进入)+pact(压紧)→压进去→冲击，影响；have an impact on 对…有影响",
    exampleSentence: "Social media has a huge impact on young people.",
    exampleTranslation: "社交媒体对年轻人有巨大影响。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "individual",
    pronunciation: "/ˌɪndɪˈvɪdʒuəl/",
    meaning: "n. 个人 adj. 个人的；独特的",
    mnemonic: "in(不)+divid(分开)+ual→不可分开的→个人",
    exampleSentence: "Each individual has the right to express their opinion.",
    exampleTranslation: "每个人都有表达意见的权利。",
    level: "CET4", tags: '["名词","形容词","真题"]', status: "published",
  },
  {
    word: "innovation",
    pronunciation: "/ˌɪnəˈveɪʃn/",
    meaning: "n. 创新，革新",
    mnemonic: "in(进入)+nov(新)+ation→进入新状态→创新",
    exampleSentence: "Technological innovation is driving economic growth.",
    exampleTranslation: "技术创新正在推动经济增长。",
    level: "CET4", tags: '["名词","热点","真题"]', status: "published",
  },
  {
    word: "inspire",
    pronunciation: "/ɪnˈspaɪər/",
    meaning: "v. 激励；启发",
    mnemonic: "in(进入)+spire(呼吸)→注入生气→激励",
    exampleSentence: "Her story inspired many people to pursue their dreams.",
    exampleTranslation: "她的故事激励了许多人追求梦想。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "investigate",
    pronunciation: "/ɪnˈvestɪɡeɪt/",
    meaning: "v. 调查，研究",
    mnemonic: "in(进入)+vestig(脚印)+ate→追踪脚印→调查",
    exampleSentence: "The police are investigating the cause of the accident.",
    exampleTranslation: "警方正在调查事故原因。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "involve",
    pronunciation: "/ɪnˈvɒlv/",
    meaning: "v. 涉及；包含；参与",
    mnemonic: "in(进入)+volve(卷)→卷入其中→涉及，参与；be involved in 参与",
    exampleSentence: "The project involves students from three different schools.",
    exampleTranslation: "这个项目涉及三所不同学校的学生。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },

  // --- L-M ---
  {
    word: "launch",
    pronunciation: "/lɔːntʃ/",
    meaning: "v./n. 发射；启动，发起",
    mnemonic: "谐音：浪起→浪起来了→启动，发起",
    exampleSentence: "The company plans to launch a new product next month.",
    exampleTranslation: "公司计划下个月推出一款新产品。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "maintain",
    pronunciation: "/meɪnˈteɪn/",
    meaning: "v. 维持；保养；坚持",
    mnemonic: "main(手)+tain(拿住)→用手拿住→维持",
    exampleSentence: "It's important to maintain a positive attitude.",
    exampleTranslation: "保持积极态度很重要。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "measure",
    pronunciation: "/ˈmeʒər/",
    meaning: "v. 测量 n. 措施",
    mnemonic: "meas(测量)+ure→测量；take measures 采取措施",
    exampleSentence: "The government has taken measures to control pollution.",
    exampleTranslation: "政府已采取措施控制污染。",
    level: "CET4", tags: '["高频词","动词","名词","真题"]', status: "published",
  },

  // --- N-O ---
  {
    word: "negative",
    pronunciation: "/ˈneɡətɪv/",
    meaning: "adj. 消极的；负面的；否定的",
    mnemonic: "neg(否定)+ative→否定的→消极的",
    exampleSentence: "Don't let negative thoughts stop you from trying.",
    exampleTranslation: "不要让消极的想法阻止你去尝试。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "negotiate",
    pronunciation: "/nɪˈɡəʊʃieɪt/",
    meaning: "v. 谈判，协商",
    mnemonic: "neg(否定)+oti(闲暇)+ate→不闲着→忙着交涉→谈判",
    exampleSentence: "The two sides are negotiating a peace agreement.",
    exampleTranslation: "双方正在谈判和平协议。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "obtain",
    pronunciation: "/əbˈteɪn/",
    meaning: "v. 获得，得到",
    mnemonic: "ob(靠近)+tain(拿住)→靠近并拿住→获得",
    exampleSentence: "You can obtain more information on our website.",
    exampleTranslation: "你可以在我们的网站上获取更多信息。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "obvious",
    pronunciation: "/ˈɒbviəs/",
    meaning: "adj. 明显的",
    mnemonic: "ob(在…前)+vi(路)+ous→摆在路前的→明显的",
    exampleSentence: "It's obvious that he needs help.",
    exampleTranslation: "很明显他需要帮助。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "opportunity",
    pronunciation: "/ˌɒpəˈtjuːnəti/",
    meaning: "n. 机会",
    mnemonic: "op(靠近)+port(港口)+unity→靠近港口的机会→机会",
    exampleSentence: "Studying abroad is a great opportunity to learn about other cultures.",
    exampleTranslation: "出国留学是了解其他文化的绝佳机会。",
    level: "CET4", tags: '["高频词","名词","真题"]', status: "published",
  },
  {
    word: "overcome",
    pronunciation: "/ˌəʊvəˈkʌm/",
    meaning: "v. 克服，战胜",
    mnemonic: "over(越过)+come(来)→越过困难过来→克服",
    exampleSentence: "We can overcome any difficulty if we work together.",
    exampleTranslation: "如果我们一起努力，就能克服任何困难。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },

  // --- P ---
  {
    word: "participate",
    pronunciation: "/pɑːˈtɪsɪpeɪt/",
    meaning: "v. 参加，参与",
    mnemonic: "part(部分)+cip(拿)+ate→拿一部分→参与；participate in 参加",
    exampleSentence: "All students are encouraged to participate in club activities.",
    exampleTranslation: "鼓励所有学生参加社团活动。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "patience",
    pronunciation: "/ˈpeɪʃns/",
    meaning: "n. 耐心",
    mnemonic: "pati(承受)+ence→承受需要耐心→耐心",
    exampleSentence: "Learning a language requires time and patience.",
    exampleTranslation: "学习语言需要时间和耐心。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "phenomenon",
    pronunciation: "/fɪˈnɒmɪnən/",
    meaning: "n. 现象（复数 phenomena）",
    mnemonic: "phen(出现)+omenon→出现的事物→现象",
    exampleSentence: "Global warming is a complex phenomenon.",
    exampleTranslation: "全球变暖是一个复杂的现象。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "potential",
    pronunciation: "/pəˈtenʃl/",
    meaning: "n. 潜力 adj. 潜在的",
    mnemonic: "potent(有力的)+ial→潜在有力的→潜力",
    exampleSentence: "Every child has the potential to succeed.",
    exampleTranslation: "每个孩子都有成功的潜力。",
    level: "CET4", tags: '["高频词","名词","形容词","真题"]', status: "published",
  },
  {
    word: "predict",
    pronunciation: "/prɪˈdɪkt/",
    meaning: "v. 预测，预言",
    mnemonic: "pre(在…之前)+dict(说)→提前说→预测",
    exampleSentence: "It's difficult to predict what will happen in the future.",
    exampleTranslation: "很难预测未来会发生什么。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "prevent",
    pronunciation: "/prɪˈvent/",
    meaning: "v. 防止，阻止",
    mnemonic: "pre(在…前)+vent(来)→提前来→防止；prevent...from 阻止…做",
    exampleSentence: "Regular exercise can help prevent many diseases.",
    exampleTranslation: "定期锻炼有助于预防许多疾病。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "promote",
    pronunciation: "/prəˈməʊt/",
    meaning: "v. 促进；推广；晋升",
    mnemonic: "pro(向前)+mote(移动)→向前移动→促进，提升",
    exampleSentence: "The campaign aims to promote healthy eating habits.",
    exampleTranslation: "这项活动旨在推广健康的饮食习惯。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "purchase",
    pronunciation: "/ˈpɜːtʃəs/",
    meaning: "v./n. 购买",
    mnemonic: "pur(完全)+chase(追赶)→完全追赶→追求到手→购买",
    exampleSentence: "You can purchase tickets online or at the door.",
    exampleTranslation: "你可以在网上或现场购票。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },

  // --- R ---
  {
    word: "recommend",
    pronunciation: "/ˌrekəˈmend/",
    meaning: "v. 推荐；建议",
    mnemonic: "re(再)+commend(称赞)→一再称赞→推荐",
    exampleSentence: "I highly recommend this book to anyone learning English.",
    exampleTranslation: "我强烈推荐这本书给所有学英语的人。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "recover",
    pronunciation: "/rɪˈkʌvər/",
    meaning: "v. 恢复；康复；找回",
    mnemonic: "re(再)+cover(覆盖)→再次覆盖→恢复",
    exampleSentence: "It took her a month to recover from the illness.",
    exampleTranslation: "她花了一个月才从病中恢复。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "reduce",
    pronunciation: "/rɪˈdjuːs/",
    meaning: "v. 减少，降低",
    mnemonic: "re(回)+duce(引导)→往回引导→减少",
    exampleSentence: "We should reduce the use of plastic bags.",
    exampleTranslation: "我们应该减少塑料袋的使用。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "reflect",
    pronunciation: "/rɪˈflekt/",
    meaning: "v. 反映；反射；反思",
    mnemonic: "re(回)+flect(弯曲)→弯曲回来→反射，反思；reflect on 反思",
    exampleSentence: "Your choice of clothes reflects your personality.",
    exampleTranslation: "你的衣着选择反映了你的个性。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "rely",
    pronunciation: "/rɪˈlaɪ/",
    meaning: "v. 依赖，依靠",
    mnemonic: "re(加强)+ly(绑)→紧紧绑在一起→依赖；rely on 依靠",
    exampleSentence: "We rely heavily on technology in our daily lives.",
    exampleTranslation: "我们在日常生活中严重依赖科技。",
    level: "CET4", tags: '["高频词","动词","真题"]', status: "published",
  },
  {
    word: "replace",
    pronunciation: "/rɪˈpleɪs/",
    meaning: "v. 取代，替代",
    mnemonic: "re(再)+place(放置)→再次放置→取代；replace A with B 用B替代A",
    exampleSentence: "Robots cannot replace human creativity.",
    exampleTranslation: "机器人无法取代人类的创造力。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "represent",
    pronunciation: "/ˌreprɪˈzent/",
    meaning: "v. 代表；表示；象征",
    mnemonic: "re(再)+present(出席)→再次出席→代表",
    exampleSentence: "The red color on the flag represents courage.",
    exampleTranslation: "国旗上的红色代表勇气。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "resource",
    pronunciation: "/rɪˈzɔːs/",
    meaning: "n. 资源（常用复数）",
    mnemonic: "re(再)+source(来源)→再次来源→资源",
    exampleSentence: "We need to use natural resources more wisely.",
    exampleTranslation: "我们需要更明智地使用自然资源。",
    level: "CET4", tags: '["高频词","名词","热点","真题"]', status: "published",
  },
  {
    word: "responsible",
    pronunciation: "/rɪˈspɒnsəbl/",
    meaning: "adj. 负责的；有责任的",
    mnemonic: "response(回应)+ible(能)→能回应的→负责的；be responsible for 对…负责",
    exampleSentence: "Everyone should be responsible for their own actions.",
    exampleTranslation: "每个人都应该对自己的行为负责。",
    level: "CET4", tags: '["高频词","形容词","真题"]', status: "published",
  },

  // --- S ---
  {
    word: "schedule",
    pronunciation: "/ˈʃedjuːl/",
    meaning: "n. 时间表 v. 安排",
    mnemonic: "谐音：死开就→死开就(让开)我要看时间表→时间表",
    exampleSentence: "I have a busy schedule this week.",
    exampleTranslation: "这周我的日程安排很满。",
    level: "CET4", tags: '["高频词","名词","动词","真题"]', status: "published",
  },
  {
    word: "significant",
    pronunciation: "/sɪɡˈnɪfɪkənt/",
    meaning: "adj. 重要的；显著的",
    mnemonic: "sign(标记)+ificant→做标记的→重要的",
    exampleSentence: "There has been a significant improvement in his grades.",
    exampleTranslation: "他的成绩有了显著提高。",
    level: "CET4", tags: '["高频词","形容词","真题"]', status: "published",
  },
  {
    word: "solution",
    pronunciation: "/səˈluːʃn/",
    meaning: "n. 解决方案；溶液",
    mnemonic: "solu(解开)+tion→解开问题的方法→解决方案",
    exampleSentence: "We need to find a solution to this problem as soon as possible.",
    exampleTranslation: "我们需要尽快找到这个问题的解决方案。",
    level: "CET4", tags: '["高频词","名词","真题"]', status: "published",
  },
  {
    word: "specific",
    pronunciation: "/spəˈsɪfɪk/",
    meaning: "adj. 具体的；特定的",
    mnemonic: "speci(种类)+fic(做)→做出种类的→具体的",
    exampleSentence: "Can you give me a specific example?",
    exampleTranslation: "你能给我一个具体的例子吗？",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "standard",
    pronunciation: "/ˈstændəd/",
    meaning: "n. 标准 adj. 标准的",
    mnemonic: "stand(站立)+ard→站着的标杆→标准",
    exampleSentence: "The company has set high standards for customer service.",
    exampleTranslation: "公司为客户服务设定了高标准。",
    level: "CET4", tags: '["名词","形容词","真题"]', status: "published",
  },
  {
    word: "strategy",
    pronunciation: "/ˈstrætədʒi/",
    meaning: "n. 策略，战略",
    mnemonic: "strat(军队)+egy→军队的谋略→战略",
    exampleSentence: "We need a new marketing strategy to attract more customers.",
    exampleTranslation: "我们需要新的营销策略来吸引更多客户。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "struggle",
    pronunciation: "/ˈstrʌɡl/",
    meaning: "v./n. 奋斗；挣扎；斗争",
    mnemonic: "strug(谐音：抓狗)+gle→抓狗是一场斗争→挣扎，奋斗",
    exampleSentence: "Many students struggle with math.",
    exampleTranslation: "许多学生在数学上挣扎。",
    level: "CET4", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "sustainable",
    pronunciation: "/səˈsteɪnəbl/",
    meaning: "adj. 可持续的",
    mnemonic: "sustain(维持)+able(能)→能维持的→可持续的",
    exampleSentence: "We need to develop more sustainable energy sources.",
    exampleTranslation: "我们需要开发更多可持续的能源。",
    level: "CET4", tags: '["形容词","热点","真题"]', status: "published",
  },

  // --- T ---
  {
    word: "target",
    pronunciation: "/ˈtɑːɡɪt/",
    meaning: "n. 目标 v. 瞄准",
    mnemonic: "tar(谐音：他)+get(得到)→他得到了目标→目标",
    exampleSentence: "Our target is to reduce waste by 50% this year.",
    exampleTranslation: "我们的目标是今年减少50%的废弃物。",
    level: "CET4", tags: '["名词","动词","真题"]', status: "published",
  },
  {
    word: "tendency",
    pronunciation: "/ˈtendənsi/",
    meaning: "n. 倾向，趋势",
    mnemonic: "tend(倾向)+ency→倾向，趋势；have a tendency to 有…的倾向",
    exampleSentence: "There is a growing tendency to work from home.",
    exampleTranslation: "在家办公的趋势越来越明显。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "transform",
    pronunciation: "/trænsˈfɔːm/",
    meaning: "v. 转变，改变",
    mnemonic: "trans(跨越)+form(形状)→改变形状→转变",
    exampleSentence: "The internet has transformed the way we communicate.",
    exampleTranslation: "互联网改变了我们的沟通方式。",
    level: "CET4", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "trend",
    pronunciation: "/trend/",
    meaning: "n. 趋势，潮流",
    mnemonic: "谐音：穿的→穿的潮流→趋势",
    exampleSentence: "There is a trend toward healthier eating habits.",
    exampleTranslation: "有一种向更健康饮食习惯发展的趋势。",
    level: "CET4", tags: '["名词","真题"]', status: "published",
  },

  // --- U-V-W ---
  {
    word: "unique",
    pronunciation: "/juːˈniːk/",
    meaning: "adj. 独特的，独一无二的",
    mnemonic: "uni(单一)+que→单一的→独特的",
    exampleSentence: "Each person has a unique set of skills and talents.",
    exampleTranslation: "每个人都有独特的技能和天赋。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "various",
    pronunciation: "/ˈveəriəs/",
    meaning: "adj. 各种各样的",
    mnemonic: "vari(变化)+ous→有变化的→各种各样的",
    exampleSentence: "The museum displays various works of art.",
    exampleTranslation: "博物馆展示了各种各样的艺术品。",
    level: "CET4", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "witness",
    pronunciation: "/ˈwɪtnəs/",
    meaning: "n. 目击者 v. 目击，见证",
    mnemonic: "wit(知道)+ness→知道事实的人→目击者",
    exampleSentence: "We are witnessing a digital revolution.",
    exampleTranslation: "我们正在见证一场数字革命。",
    level: "CET4", tags: '["名词","动词","真题"]', status: "published",
  },
];

// ============================================================
// CET-6 高频词汇 (2020-2026 真题高频)
// ============================================================
export const cet6Words: WordSeed[] = [
  {
    word: "acknowledge",
    pronunciation: "/əkˈnɒlɪdʒ/",
    meaning: "v. 承认；致谢",
    mnemonic: "ac(加强)+knowledge(知识)→加强认知→承认",
    exampleSentence: "He finally acknowledged his mistake.",
    exampleTranslation: "他终于承认了自己的错误。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "acquire",
    pronunciation: "/əˈkwaɪər/",
    meaning: "v. 获得；习得",
    mnemonic: "ac(朝向)+quire(寻求)→去寻求→获得",
    exampleSentence: "It takes years to acquire a new language fluently.",
    exampleTranslation: "流利掌握一门新语言需要多年时间。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "advocate",
    pronunciation: "/ˈædvəkeɪt/",
    meaning: "v. 提倡，主张 n. 倡导者",
    mnemonic: "ad(朝向)+voc(喊)+ate→朝着…喊→提倡",
    exampleSentence: "He advocates for better mental health services.",
    exampleTranslation: "他提倡更好的心理健康服务。",
    level: "CET6", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "alternative",
    pronunciation: "/ɔːlˈtɜːnətɪv/",
    meaning: "n. 替代品 adj. 替代的",
    mnemonic: "alter(改变)+native→改变后的选择→替代品",
    exampleSentence: "We need to find alternative energy sources.",
    exampleTranslation: "我们需要找到替代能源。",
    level: "CET6", tags: '["高频词","名词","形容词","真题"]', status: "published",
  },
  {
    word: "ambitious",
    pronunciation: "/æmˈbɪʃəs/",
    meaning: "adj. 有雄心的，野心勃勃的",
    mnemonic: "ambi(两边)+tious→两边都想要→有雄心的",
    exampleSentence: "She is an ambitious young entrepreneur.",
    exampleTranslation: "她是一位有雄心的年轻企业家。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "anticipate",
    pronunciation: "/ænˈtɪsɪpeɪt/",
    meaning: "v. 预期，预料；先于…行动",
    mnemonic: "anti(在…之前)+cip(拿)+ate→提前拿到→预期",
    exampleSentence: "We anticipate that sales will increase next quarter.",
    exampleTranslation: "我们预计下季度销售额将增长。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "assess",
    pronunciation: "/əˈses/",
    meaning: "v. 评估，评定",
    mnemonic: "as(朝向)+sess(坐)→坐下来评判→评估",
    exampleSentence: "The teacher will assess the students' progress at the end of the term.",
    exampleTranslation: "老师将在学期末评估学生的进步。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "attribute",
    pronunciation: "/əˈtrɪbjuːt/",
    meaning: "v. 归因于 n. 属性",
    mnemonic: "at(朝向)+tribute(给予)→给予…→归因于；attribute to 归因于",
    exampleSentence: "His success can be attributed to hard work and perseverance.",
    exampleTranslation: "他的成功可归因于努力和毅力。",
    level: "CET6", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "collapse",
    pronunciation: "/kəˈlæps/",
    meaning: "v./n. 倒塌；崩溃；暴跌",
    mnemonic: "col(一起)+lapse(滑倒)→一起滑倒→倒塌，崩溃",
    exampleSentence: "The building collapsed during the earthquake.",
    exampleTranslation: "这栋建筑在地震中倒塌了。",
    level: "CET6", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "comprehensive",
    pronunciation: "/ˌkɒmprɪˈhensɪv/",
    meaning: "adj. 全面的，综合的",
    mnemonic: "com(一起)+prehens(抓住)+ive→一起抓住的→全面的",
    exampleSentence: "We need a comprehensive plan to solve this issue.",
    exampleTranslation: "我们需要一个全面的计划来解决这个问题。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "conservation",
    pronunciation: "/ˌkɒnsəˈveɪʃn/",
    meaning: "n. 保护；节约",
    mnemonic: "con(一起)+serv(保持)+ation→一起保持→保护",
    exampleSentence: "Wildlife conservation is crucial for biodiversity.",
    exampleTranslation: "野生动物保护对生物多样性至关重要。",
    level: "CET6", tags: '["名词","热点","真题"]', status: "published",
  },
  {
    word: "controversial",
    pronunciation: "/ˌkɒntrəˈvɜːʃl/",
    meaning: "adj. 有争议的",
    mnemonic: "contro(反对)+vers(转向)+ial→转向反对的→有争议的",
    exampleSentence: "The new policy has been highly controversial.",
    exampleTranslation: "新政策一直极具争议。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "dilemma",
    pronunciation: "/dɪˈlemə/",
    meaning: "n. 困境，进退两难",
    mnemonic: "di(两个)+lemma(论点)→两个论点之间→进退两难",
    exampleSentence: "He faced the dilemma of choosing between his career and his family.",
    exampleTranslation: "他面临在事业和家庭之间选择的困境。",
    level: "CET6", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "domestic",
    pronunciation: "/dəˈmestɪk/",
    meaning: "adj. 国内的；家庭的",
    mnemonic: "dom(家)+estic→家的→国内的，家庭的",
    exampleSentence: "The domestic economy has recovered quickly from the crisis.",
    exampleTranslation: "国内经济已从危机中迅速恢复。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "enhance",
    pronunciation: "/ɪnˈhɑːns/",
    meaning: "v. 提高，增强",
    mnemonic: "en(使)+hance(高)→使变高→提高，增强",
    exampleSentence: "Regular reading can enhance your vocabulary significantly.",
    exampleTranslation: "定期阅读能显著增强你的词汇量。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "inevitable",
    pronunciation: "/ɪnˈevɪtəbl/",
    meaning: "adj. 不可避免的",
    mnemonic: "in(不)+evitable(可避免的)→不可避免的",
    exampleSentence: "Change is an inevitable part of life.",
    exampleTranslation: "变化是生活中不可避免的一部分。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "perspective",
    pronunciation: "/pəˈspektɪv/",
    meaning: "n. 观点；视角；透视",
    mnemonic: "per(穿过)+spect(看)+ive→看穿→视角，观点",
    exampleSentence: "Traveling gives you a new perspective on life.",
    exampleTranslation: "旅行让你对生活有新的视角。",
    level: "CET6", tags: '["高频词","名词","真题"]', status: "published",
  },
  {
    word: "profound",
    pronunciation: "/prəˈfaʊnd/",
    meaning: "adj. 深刻的；深远的",
    mnemonic: "pro(向前)+found(底部)→向前到底→深刻的",
    exampleSentence: "The book had a profound influence on my thinking.",
    exampleTranslation: "这本书对我的思想产生了深远的影响。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "prosperity",
    pronunciation: "/prɒˈsperəti/",
    meaning: "n. 繁荣，兴旺",
    mnemonic: "pro(向前)+sper(希望)+ity→希望在前→繁荣",
    exampleSentence: "Education is the key to national prosperity.",
    exampleTranslation: "教育是国家繁荣的关键。",
    level: "CET6", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "revenue",
    pronunciation: "/ˈrevənjuː/",
    meaning: "n. 收入；税收",
    mnemonic: "re(回)+venue(来)→收回来的东西→收入",
    exampleSentence: "The company's revenue increased by 20% this year.",
    exampleTranslation: "公司今年的收入增长了20%。",
    level: "CET6", tags: '["名词","真题"]', status: "published",
  },
  {
    word: "simultaneously",
    pronunciation: "/ˌsɪmlˈteɪniəsli/",
    meaning: "adv. 同时地",
    mnemonic: "simul(相同)+taneous+ly→相同时间→同时地",
    exampleSentence: "She can listen to music and study simultaneously.",
    exampleTranslation: "她能边听音乐边学习。",
    level: "CET6", tags: '["副词","真题"]', status: "published",
  },
  {
    word: "substantial",
    pronunciation: "/səbˈstænʃl/",
    meaning: "adj. 大量的；实质的",
    mnemonic: "sub(在…下)+stant(站立)+ial→站在下面的→实质的",
    exampleSentence: "There has been a substantial increase in online learning.",
    exampleTranslation: "在线学习有了大幅增长。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
  {
    word: "surrender",
    pronunciation: "/səˈrendər/",
    meaning: "v./n. 投降；放弃",
    mnemonic: "sur(在…上)+render(给予)→向上给出→投降",
    exampleSentence: "The soldiers refused to surrender to the enemy.",
    exampleTranslation: "士兵们拒绝向敌人投降。",
    level: "CET6", tags: '["动词","名词","真题"]', status: "published",
  },
  {
    word: "verify",
    pronunciation: "/ˈverɪfaɪ/",
    meaning: "v. 核实，验证",
    mnemonic: "veri(真实)+fy(使)→使真实→核实",
    exampleSentence: "Please verify your email address before continuing.",
    exampleTranslation: "请在继续之前验证您的邮箱地址。",
    level: "CET6", tags: '["动词","真题"]', status: "published",
  },
  {
    word: "vulnerable",
    pronunciation: "/ˈvʌlnərəbl/",
    meaning: "adj. 脆弱的；易受伤的",
    mnemonic: "vulner(伤口)+able(容易)→容易受伤的→脆弱的",
    exampleSentence: "Children are particularly vulnerable to online dangers.",
    exampleTranslation: "儿童特别容易受到网络危险的伤害。",
    level: "CET6", tags: '["形容词","真题"]', status: "published",
  },
];

// ============================================================
// 四六级短文 (2020-2026 热点话题)
// ============================================================
export const passages: PassageSeed[] = [
  {
    title: "A Day on Campus",
    content: "Every morning, I walk across the campus with a brilliant smile. The academic atmosphere here helps me absorb new knowledge quickly. I never abandon my study plan, even when it's hard to calculate the time needed for each subject. My professors always encourage us to explore diverse fields and embrace new challenges.",
    translation: "每天早晨，我带着灿烂的笑容走过校园。这里的学术氛围帮助我快速吸收新知识。我从不放弃学习计划，即使很难计算每个科目所需的时间。我的教授总是鼓励我们探索不同领域并拥抱新的挑战。",
    highlightedWordIds: "[1,2,3,4,5,6,7,8,9]",
    level: "CET4", tags: '["校园生活","日常","真题"]', status: "published",
  },
  {
    title: "Digital Life in Modern Society",
    content: "Digital technology has transformed our daily lives in significant ways. We rely on smartphones to communicate, shop, and access information. However, we must maintain a balance between online and offline activities. Many people struggle to reduce their screen time, which can negatively impact their health. It is essential to develop healthy digital habits and focus on real-world relationships.",
    translation: "数字技术以显著的方式改变了我们的日常生活。我们依赖智能手机进行交流、购物和获取信息。然而，我们必须保持线上和线下活动的平衡。许多人在减少屏幕时间方面挣扎，这可能会对健康产生负面影响。培养健康的数字习惯并专注于现实世界的关系至关重要。",
    highlightedWordIds: "[10,11,12,13,14,15,16,17,18]",
    level: "CET4", tags: '["科技","社会","热点","真题"]', status: "published",
  },
  {
    title: "Environmental Protection",
    content: "Environmental protection has become a global priority in recent years. Governments have taken various measures to reduce pollution and promote sustainable development. Individual actions also contribute significantly to this cause. We can reduce plastic waste, save energy, and choose eco-friendly products. Every small step matters when it comes to protecting our planet for future generations.",
    translation: "环境保护近年来已成为全球优先事项。各国政府采取了各种措施来减少污染并促进可持续发展。个人行动也对这一事业有重大贡献。我们可以减少塑料废弃物、节约能源并选择环保产品。在为子孙后代保护地球方面，每一小步都很重要。",
    highlightedWordIds: "[19,20,21,22,23,24,25,26]",
    level: "CET4", tags: '["环保","社会","热点","真题"]', status: "published",
  },
  {
    title: "The Power of Lifelong Learning",
    content: "In today's rapidly changing world, learning should not stop after graduation. Lifelong learning is essential for personal growth and career development. The advancement of online education platforms has made learning more accessible than ever. People can now acquire new skills, explore different subjects, and enhance their professional abilities at their own pace. This trend reflects a fundamental shift in how we approach education.",
    translation: "在当今快速变化的世界中，学习不应在毕业后停止。终身学习对个人成长和职业发展至关重要。在线教育平台的进步使学习比以往任何时候都更容易获得。人们现在可以按照自己的节奏获取新技能、探索不同学科并提高专业能力。这一趋势反映了我们对待教育方式的根本转变。",
    highlightedWordIds: "[27,28,29,30,31,32,33,34]",
    level: "CET6", tags: '["教育","社会","热点","真题"]', status: "published",
  },
  {
    title: "Overcoming Challenges in College",
    content: "College life presents students with various challenges, from academic pressure to social adjustment. It is critical to develop effective strategies for managing time and stress. Many students struggle to balance study, social activities, and part-time jobs. However, these challenges also provide valuable opportunities for personal growth. With patience and determination, every student can overcome difficulties and achieve their goals.",
    translation: "大学生活给学生带来了各种挑战，从学业压力到社交适应。制定有效的时间管理和压力应对策略至关重要。许多学生在平衡学习、社交活动和兼职工作方面挣扎。然而，这些挑战也为个人成长提供了宝贵的机会。只要有耐心和决心，每个学生都能克服困难并实现目标。",
    highlightedWordIds: "[35,36,37,38,39,40,41,42]",
    level: "CET4", tags: '["校园生活","成长","真题"]', status: "published",
  },
  {
    title: "The Impact of Social Media",
    content: "Social media has fundamentally changed how we interact with each other. It allows us to connect with people across the globe and share experiences instantly. However, evidence suggests that excessive use of social media can lead to negative consequences, including anxiety and decreased productivity. We must learn to use these platforms responsibly and maintain authentic relationships beyond the digital world.",
    translation: "社交媒体从根本上改变了我们彼此互动的方式。它让我们能与全球各地的人联系并即时分享经历。然而，有证据表明过度使用社交媒体可能导致负面后果，包括焦虑和生产力下降。我们必须学会负责任地使用这些平台，并在数字世界之外维持真实的关系。",
    highlightedWordIds: "[43,44,45,46,47,48,49]",
    level: "CET6", tags: '["科技","社会","热点","真题"]', status: "published",
  },
  {
    title: "Career Planning for College Students",
    content: "Career planning should begin early in college rather than waiting until graduation. Students are encouraged to participate in internships, volunteer activities, and career workshops to explore their interests. Identifying one's strengths and weaknesses is an important first step. The job market is highly competitive, so gaining practical experience can give graduates a significant advantage. Remember that flexibility is key — many successful professionals have changed career paths multiple times.",
    translation: "职业规划应该在大学早期开始，而不是等到毕业。鼓励学生参加实习、志愿者活动和职业工作坊来探索自己的兴趣。识别自己的优势和劣势是重要的第一步。就业市场竞争激烈，因此积累实践经验可以给毕业生带来显著优势。记住，灵活性是关键——许多成功的专业人士曾多次改变职业道路。",
    highlightedWordIds: "[50,51,52,53,54,55,56,57]",
    level: "CET6", tags: '["职业","校园","真题"]', status: "published",
  },
  {
    title: "Global Warming and Our Responsibility",
    content: "Global warming is one of the most pressing issues of our time. Scientists predict that if we fail to reduce carbon emissions, the consequences could be devastating. Rising temperatures are already causing extreme weather events, melting glaciers, and threatening biodiversity. As individuals, we can contribute to the solution by adopting more sustainable lifestyles. Governments and businesses must also take bold measures to address this global challenge.",
    translation: "全球变暖是我们这个时代最紧迫的问题之一。科学家预测，如果我们未能减少碳排放，后果可能是灾难性的。不断上升的气温已经在导致极端天气事件、冰川融化和生物多样性受威胁。作为个人，我们可以通过采取更可持续的生活方式为解决方案做出贡献。政府和企业也必须采取大胆措施来应对这一全球性挑战。",
    highlightedWordIds: "[58,59,60,61,62,63,64,65]",
    level: "CET6", tags: '["环保","社会","热点","真题"]', status: "published",
  },
  {
    title: "The Art of Time Management",
    content: "Effective time management is a fundamental skill that benefits every aspect of life. Students who manage their time well tend to achieve better academic results and experience less stress. The key is to prioritize tasks, set realistic goals, and avoid procrastination. Creating a weekly schedule and sticking to it can transform your productivity. Remember that rest is also an essential part of any productive routine.",
    translation: "有效的时间管理是一项使生活各方面受益的基本技能。善于管理时间的学生往往能取得更好的学业成绩并经历更少的压力。关键是确定任务的优先顺序、设定现实的目标并避免拖延。创建每周计划并坚持执行可以改变你的生产力。记住，休息也是任何高效日常安排的重要组成部分。",
    highlightedWordIds: "[66,67,68,69,70,71,72,73]",
    level: "CET4", tags: '["学习方法","校园","真题"]', status: "published",
  },
  {
    title: "Innovation and Entrepreneurship",
    content: "Innovation drives economic growth and social progress. In recent years, we have witnessed a surge in entrepreneurial activities among young people. College graduates are increasingly choosing to launch their own startups instead of seeking traditional employment. While this path involves significant risks, it also offers tremendous opportunities for those with creative ideas and determination. Society should encourage this spirit of innovation and provide better support for young entrepreneurs.",
    translation: "创新驱动经济增长和社会进步。近年来，我们目睹了年轻人创业活动的激增。大学毕业生越来越多地选择创办自己的初创公司，而不是寻求传统就业。虽然这条道路涉及重大风险，但它也为那些有创意想法和决心的人提供了巨大的机会。社会应鼓励这种创新精神，并为年轻创业者提供更好的支持。",
    highlightedWordIds: "[74,75,76,77,78,79,80,81]",
    level: "CET6", tags: '["创业","经济","热点","真题"]', status: "published",
  },
];
